spring:
  # 默认开发环境
  profiles:
    active: dev
  jpa:
    # 展示sql
    show-sql: true
  messages:
    basename: i18n/messages/messages
    encoding: UTF-8
    fallbackToSystemLocale: true
  #  用于数据库表结构版本管理
  flyway:
    locations: classpath:db/migration
  jmx:
    enabled: false
ali:
  dbhub:
    version: 1.0.0
# flywaydb 输出执行sql的日志
logging:
  level:
    org:
      flywaydb: debug