spring:
  # 默认开发环境
  profiles:
    active: dev
  datasource:
    # 配置自带数据库的相对路径
    url: jdbc:h2:~/.data-ops/db/data_ops;MODE=MYSQL
    driver-class-name: org.h2.Driver
  jpa:
    # 展示sql
    show-sql: true
  messages:
    basename: i18n/messages/messages
    encoding: UTF-8
    fallbackToSystemLocale: true
  #  用于数据库表结构版本管理
  flyway:
    locations: classpath:db/migration
  jmx:
    enabled: false
data:
  ops:
    version: 1.0.0
# flywaydb 输出执行sql的日志
logging:
  level:
    org:
      flywaydb: debug