spring:
  datasource:
    # 配置自带数据库的相对路径
    url: jdbc:h2:~/.data-ops/db/data_ops;MODE=MYSQL
    driver-class-name: org.h2.Driver
  jpa:
    # 展示sql
    show-sql: true
  messages:
    basename: i18n/messages/messages
    encoding: UTF-8
    fallbackToSystemLocale: true
  h2:
    console:
      enabled: true
      path: /h2
      settings:
        trace: true
        web-allow-others: true
  flyway:
    locations: classpath:db/migration
  jmx:
    enabled: false
server:
  port: 10824
# flywaydb 输出执行sql的日志
logging:
  level:
    org:
      flywaydb: debug