version: '3'
services:
  # 运行mysql数据库，用户名：root  密码 ：ali_dbhub 端口：3306
  mysql:
    image: mysql:latest
    restart: always
    container_name: mysql-latest
    environment:
      - "MYSQL_ROOT_PASSWORD=ali_dbhub"
      - "MYSQL_DATABASE=ali_dbhub_test"
      - "TZ=Asia/Shanghai"
    ports:
      - 3306:3306