# Workflow's name
name: OSS test

# Workflow's trigger
# 在创建标签的时候触发打包
# main 分支打包release的
# 其他分支统一打包test的
on: [push, pull_request]

# Workflow's jobs
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@main


      # 把文件上传到OSS 方便下载
      - name: Set up oss utils
        uses: yizhoumo/setup-ossutil@v1
        with:
          endpoint: "oss-cn-zhangjiakou.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          ossutil-version: 'latest'
      - name: Upload to oss
        run: ossutil cp -rf --acl=public-read ali-dbhub-client/ oss://chat2db/release/
