# Workflow's name
name: OSS test

# Workflow's trigger
# 在创建标签的时候触发打包
# main 分支打包release的
# 其他分支统一打包test的
on:
  push:
    tags:
      - *

# Workflow's jobs
jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: Check out git repository
        uses: actions/checkout@main

      # 获取版本号 workflow不支持 所以用插件
      - name: substring-action
        id: chat2db_version
        uses: bhowell2/github-substring-action@1.0.1
        with:
          value: ${{ github.ref }}
          index_of_str: "refs/tags/"

      # 把文件上传到OSS 方便下载
      - name: Set up oss utils
        uses: yizhoumo/setup-ossutil@v1
        with:
          endpoint: "chat2db.oss-accelerate.aliyuncs.com"
          access-key-id: ${{ secrets.OSS_ACCESS_KEY_ID }}
          access-key-secret: ${{ secrets.OSS_ACCESS_KEY_SECRET }}
          ossutil-version: 'latest'
      - name: Upload to oss
        run: |
          ossutil cp -rf --acl=public-read ali-dbhub-client/electron/login/logo oss://chat2db/release/${{ steps.chat2db_version.outputs.substring }}/
#          ossutil cp -rf --acl=public-read ali-dbhub-client/electron/app/ali-dbhub-server-start.jar oss://chat2db/release/${{ steps.chat2db_version.outputs.substring }}/
#          ossutil cp -rf --acl=public-read ali-dbhub-client/electron-build/*.dmg oss://chat2db/release/${{ steps.chat2db_version.outputs.substring }}/
#          ossutil cp -rf --acl=public-read ali-dbhub-client/electron/app/ali-dbhub-client/electron-build/*Setup*.exe oss://chat2db/release/${{ steps.chat2db_version.outputs.substring }}/