# Workflow's name
name: Push to docker

# Workflow's trigger
on:
  release:
    types: [published]

# Workflow's jobs
jobs:
  docker:
    runs-on: ubuntu-latest
    steps:
      # 获取版本号 workflow不支持 所以用插件
      - name: Create version
        id: chat2db_version
        uses: bhowell2/github-substring-action@1.0.1
        with:
          value: ${{ github.ref }}
          index_of_str: "refs/tags/v"

      - name: Set up QEMU
        uses: docker/setup-qemu-action@v2
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      # 登录docker hub
      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      # 打包发送到docker
      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          push: true
          tags: chat2db/chat2db:${{ steps.chat2db_version.outputs.substring }}
          file: docker/Dockerfile
