

name: release

on: [ push, pull_request ]

jobs:
  publish:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@main
      - name: Install Java and Maven
        uses: actions/setup-java@main
        with:
          java-version: 8
          distribution: 'adopt'
          java-package: jre
          cache: maven
      - name: Test with Maven22
        run: echo $JAVA_HOME
      - name: Test with Maven22
        run: ls $JAVA_HOME
      - name: Build Java
        run: mvn clean package -B -Dmaven.test.skip=true -f data-ops-server/pom.xml