# Workflow's name
name: Build Client

# Workflow's trigger
# on: [push, pull_request]
on:
  push:
    tags:
      - v*

# Workflow's jobs
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ macos-latest ]

    steps:
      - name: Check out git repository
        uses: actions/checkout@main
      # 安装java
      - name: Install Java and Maven
        uses: actions/setup-java@main
        with:
          java-version: '17'
          distribution: 'adopt'
          cache: 'maven'

      # 编译服务端java版本
      - name: Build Java
        run: mvn clean package -B -Dmaven.test.skip=true -f data-ops-server/pom.xml

      # 打包jre
      - name: Build jre
        run: jlink --add-modules java.base,java.management,java.naming,java.net.http,java.desktop,java.security.jgss,java.security.sasl,java.sql,jdk.httpserver,jdk.unsupported,java.instrument --output jre --no-man-pages --no-header-files --compress=2

      # 复制jre & 服务端java 到制修订位置
      - name: Copy app &  jre
        run: |
          cp -r jre data-ops-client/electron/
          mkdir data-ops-client/electron/app
          cp data-ops-server/data-ops-server-start/target/data-ops-server-start.jar data-ops-client/electron/app/

      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version: 16
          # cache: "yarn"
          # cache-dependency-path: data-ops-client/yarn.lock

      - name: npm install & build
        run: |
          cd ~/work/data-ops/data-ops/data-ops-client
          npm install 
          npm run build

      - name: npm install electron
        run: |
          cd ~/work/data-ops/data-ops/data-ops-client/electron
          rm -rf ../electron-build && cp -r ../dist ./
          yarn

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          package_root: "./data-ops-client/electron"
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          GITHUB_TOKEN: ${{ secrets.ACCESS_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}

      - name: upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: dataOps-mac
          path: ~/work/data-ops/data-ops/data-ops-client/electron-build/**
          if-no-files-found: ignore
