# Workflow's name
name: Build Client

# Workflow's trigger
# on: [push, pull_request]
on:
  push:
    tags:
      - v*

# Workflow's jobs
jobs:
  release:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest]

    steps:
      - name: Check out git repository
        uses: actions/checkout@main

      - name: Install Node.js
        uses: actions/setup-node@main
        with:
          node-version: 16
          cache: "yarn"
          # cache-dependency-path: data-ops-client/yarn.lock

      - name: npm install & build
        run: |
          cd ~/work/data-ops/data-ops/data-ops-client
          npm install 
          npm run build

      - name: npm install electron
        run: |
          cd ~/work/data-ops/data-ops/data-ops-client/electron
          npm install
          npm run build

      - name: Build/release Electron app
        uses: samuelmeuli/action-electron-builder@v1
        with:
          # GitHub token, automatically provided to the action
          # (No need to define this secret in the repo settings)
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

          # If the commit is tagged with a version (e.g. "v1.0.0"),
          # release the app after building
          release: ${{ startsWith(github.ref, 'refs/tags/v') }}
          mac_certs: ${{ secrets.mac_certs }}
          mac_certs_password: ${{ secrets.mac_certs_password }}

      - name: upload artifacts
        uses: actions/upload-artifact@main
        with:
          name: dataOps-mac
          path: ~/work/data-ops/data-ops/data-ops-client/electron-build/**
          if-no-files-found: ignore
